-- Sales - by farm.csv  — load-grain reconciliation. Report = Sell dispatch loads (order_type='S'),
-- one line per (load, product). Mapping (proven): [4]=load_no, [5]=order_no, [14]=qty (boxes),
-- [16]=net weight, [15]=amount $, [10]=unit price. load_no is UNIQUE in raw.ft_dispatch_load.

-- (A) Spot check — 3 lines map exactly to warehouse stock_boxes / Σbox_count / Σnet_weight:
--     Simped order 5009135 -> 3024 boxes / 30240 kg ; Sage 5022695 -> 1 / 15 ; Week27 5022696 -> 55 / 445.5
select d.order_no, d.load_no, d.order_type, d.stock_boxes,
       (select sum(p.box_count) from raw.ft_pallet p where p.dispatch_load_id=d.id) box_sum,
       (select sum(p.net_weight_value) from raw.ft_pallet p where p.dispatch_load_id=d.id) netwt
from raw.ft_dispatch_load d
where d.order_no in ('5009135','5022695','5022696');

-- (B) Full reconciliation (the giant load_no VALUES list is generated by reconciliation/salesfarm_extract.ts;
--     run: node --experimental-strip-types reconciliation/salesfarm_extract.ts > q.sql ; q.ts -f q.sql).
--     Logic: aggregate report by load_no (Σ col14 qty, Σ col16 weight), join 1:1 to the warehouse load,
--     compare to stock_boxes + reconsigned_boxes (the col14 basis) and Σ net_weight_value.
--   RESULT: report qty 4,919,304 vs wh stock+recon 4,898,389 (0.43%); 8391/8572 loads exact.
--           report weight 53,495,382 vs wh net_weight 55,315,194 (+3.4%); 5895/8579 within 1%.

-- (C) Why col14 = stock_boxes + reconsigned_boxes (not stock alone): reconsigned boxes are sold-through.
--     col13 in the CSV is the ORDER-level total REPEATED on each split row (480+840=1320) — a render
--     artifact, NOT a measure; do not sum it.

-- (D) Weight residual cause: warehouse net_weight_value is unreliable for some carton configs (SPEC §9.3) —
--     e.g. load 5011173: 15kg cartons recorded at 24.6–90 kg/box, ~2x the report's boxes x nominal weight.
select p.product_description, count(*) pallets, sum(p.box_count) boxes, sum(p.net_weight_value) netwt,
       round(sum(p.net_weight_value)/nullif(sum(p.box_count),0),2) kg_per_box
from raw.ft_dispatch_load d join raw.ft_pallet p on p.dispatch_load_id=d.id
where d.load_no='5011173' group by p.product_description;

-- (E) Amount $ (85,522,918) + unit price: BLOCKED — same as Weekly PO. amount = col14 qty x price, and price
--     lives in FreshTrack order_item.price_value / total_price_value (NOT landed in the warehouse).
--     Proof (FreshTrack replica, reconciliation/ftq.ts): order 5009135 line price_value 24.90, total 75297.60.
